name: Build and push firmware

on:
  workflow_call:
    outputs:
      artifact_name:
        value: "grid_esp32_fw.uf2"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Build ESP32 firmware
        run: docker run -v $PWD:/project -w /project/ ghcr.io/${{ github.repository }}:${{ github.ref_name }} sh -c "./lua_build.sh && ./pico_build.sh && ./esp_build.sh"
