name: Build and push firmware

on:
  workflow_call:
    outputs:
      artifact_name:
        value: "grid_esp32_fw.uf2"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - name: Build ESP32 firmware
        run: |
          ./lua_build.sh
          ./pico_build.sh
          ./esp_build.sh
