name: Build and push firmware

on:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Set image tag environment variable
        run: echo "IMAGE_TAG=$(basename ${{ github.ref }})" >> $GITHUB_ENV

      - name: Set image environment variable
        run: echo "IMAGE_PATH=ghcr.io/${{ github.repository_owner }}/grid-firmware:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ${{ env.IMAGE_PATH }}

      - name: Build ESP32 firmware
        run: docker run -v $PWD:/project -w /project/ ${{ env.IMAGE_PATH }} sh -c \
          "./lua_build.sh && ./pico_build.sh && ./esp_build.sh"
