name: Build and push firmware

on:
  workflow_call:
    inputs:
      image-name:
        description: Image name
        required: true
        type: string
      dockerfile:
        description: Path to the Dockerfile
        required: true
        type: string
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      image: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:latest
      label: org.opencontainers.image.revision
    steps:

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull or rebuild image
        run: |
          if docker pull ${{ env.image }} ; then
            SHA=$(docker inspect $IMAGE --format '{{ index .Config.Labels "${{ env.label }}" }}')
            if [ -n "$(git diff $SHA ${{ github.sha }} -- ${{ inputs.dockerfile }})" ] ; then
              docker build --label ${{ env.label }}=${{ github.sha }} -t ${{ env.image }} .
              if [ "${{ github.ref_name }}" = "main" ] ; then
                docker push ${{ env.image }}
              fi
            fi
          fi

      - name: Build ESP32 firmware
        run: |
          docker run -v $PWD:/project -w /project ${{ env.image }} \
          sh -c "./lua_build.sh && ./pico_build.sh"

