name: Push components to espressif registry

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - 'common/src/**'
      - 'esp32/components/**'
      - '.github/workflows/idf-repository-package-update.yml'

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set Date
        run: echo "action_date=$(date +v%Y.%-m.%-d%H%M)" >> $GITHUB_ENV

      - name: Check Date
        run: echo ${{ env.action_date }}

      - name: Convert native lua sources to C headers
        run: ./lua_build.sh

      - name: Replace symbolic link in grid_common with a recursive copy
        run: |
          rm esp32/components/grid_common/common
          cp -r common esp32/components/grid_common

      - name: Upload components to the component registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: |
            grid_common:esp32/components/grid_common
            grid_esp32_led:esp32/components/grid_esp32_led
            grid_esp32_nvm:esp32/components/grid_esp32_nvm
            grid_esp32_littlefs:esp32/components/grid_esp32_littlefs
          namespace: "benblaise-intech"
          version: ${{ env.action_date }}
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
