name: Publish firmware

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-firmware:
    name: Build firmware
    uses: ./.github/workflows/build-and-push-firmware.yml
