name: Publish firmware

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-firmware:
    name: Build firmware
    uses: ./.github/workflows/build-and-push-firmware.yml

  publish-stable:
    name: Publish stable release
    needs: build-firmware
    if: needs.build-firmware.outputs.version_tag
    uses: ./.github/workflows/publish-stable-firmware.yml
    with:
      product_name: "grid"
      version_tag: ${{ needs.build-firmware.outputs.version_tag }}
      timestamp: ${{ needs.build-firmware.outputs.timestamp }}
    secrets: inherit
